server {
    listen 127.0.0.1:8080;

    root ./www;
    index index.html;

    client_max_body_size 1048576;

    error_page 404 ./errors/404.html;

    location / {
        methods GET HEAD;
        autoindex off;
    }

    location /static {
        methods GET HEAD;
        root ./www/static;
        autoindex on;
    }

    location /listing {
        methods GET;
        root ./www/listing;
        autoindex on;
    }

    location /old {
        methods GET;
        return 301 /index.html;
    }

    location /small {
        methods POST;
        upload_store ./uploads;
        client_max_body_size 100;
    }

    location /upload {
        methods GET POST DELETE;
        root ./uploads;
        upload_store ./uploads;
        autoindex on;
    }

    location /cgi-bin {
        methods GET POST HEAD;
        root ./cgi-bin;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }

    location /cgi-sh {
        methods GET POST HEAD;
        root ./cgi-bin;
        cgi_extension .sh;
        cgi_path /bin/sh;
    }

    location /cgi-pl {
        methods GET POST HEAD;
        root ./cgi-bin;
        cgi_extension .pl;
        cgi_path /usr/bin/perl;
    }

    location /cgi-exe {
        methods GET POST HEAD;
        root ./cgi-bin;
        cgi_extension .bin;
        cgi_path ./cgi-bin/hello_bin;
    }

    location /session {
        methods GET;
    }
}

server {
    listen 127.0.0.1:8081;

    root ./www/site-b;
    index index.html;

    location / {
        methods GET;
        autoindex on;
    }
}
