server {
    listen 127.0.0.1:8080;

    root ./www;
    index index.html;


    error_page 404 ./errors/404.html;

    location / {
        methods GET;
        autoindex off;
    }

    location /post_body {
        methods POST;
        upload_store ./uploads;
        client_max_body_size 100;
    }

    location /directory {
        client_max_body_size 200000000;
        methods GET POST;
        root ./YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
        cgi_extension .bla;
        cgi_path ./cgi_test;
    }
}
